name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - wheel-build-pylibcugraph
      - wheel-build-cugraph
      - wheel-build-nx-cugraph
      - wheel-build-cugraph-dgl
      - wheel-build-cugraph-pyg
      - wheel-build-cugraph-equivariant
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-24.12
    if: always()
    with:
      needs: ${{ toJSON(needs) }}
  wheel-build-pylibcugraph:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.12
    with:
      build_type: pull-request
      script: ci/build_wheel_pylibcugraph.sh
      extra-repo: rapidsai/cugraph-ops
      extra-repo-sha: branch-24.12
      extra-repo-deploy-key: CUGRAPH_OPS_SSH_PRIVATE_DEPLOY_KEY
      node_type: cpu32
  wheel-build-cugraph:
    needs: wheel-build-pylibcugraph
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.12
    with:
      build_type: pull-request
      script: ci/build_wheel_cugraph.sh
      extra-repo: rapidsai/cugraph-ops
      extra-repo-sha: branch-24.12
      extra-repo-deploy-key: CUGRAPH_OPS_SSH_PRIVATE_DEPLOY_KEY
  wheel-build-nx-cugraph:
    needs: wheel-build-cugraph
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.12
    with:
      build_type: pull-request
      script: ci/build_wheel_nx-cugraph.sh
  wheel-build-cugraph-dgl:
    needs: wheel-build-cugraph
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.12
    with:
      build_type: pull-request
      script: ci/build_wheel_cugraph-dgl.sh
  wheel-build-cugraph-pyg:
    needs: wheel-build-cugraph
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.12
    with:
      build_type: pull-request
      script: ci/build_wheel_cugraph-pyg.sh
  wheel-build-cugraph-equivariant:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.12
    with:
      build_type: pull-request
      script: ci/build_wheel_cugraph-equivariant.sh
